apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: repset-test
  labels:
    app: rep-set1
    type: front-end
spec:
  replicas: 3
  selector:
     matchLabels:
      type: front-end
  template:
    metadata:
      name: rep-set3
      labels:
        app: rep-set1
        type: front-end
    spec:
      containers:
        - name: repcon
          image: nginx
