apiVersion: v1
kind: ReplicationController
metadata:
  name: rep-test
  labels:
    app: reptest
    type: frontend
spec:
  template:
    metadata:
      name: repocreation
      labels:
        hi: hello
        bye: goodbye
    spec:
      containers:
        - name: con1
          image: nginx
  replicas: 3