apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deploy
  labels:
    app: redis-deploy
    type: redis-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-app
      type: voting-app-demo
  template:
    metadata:
      name: redis-app-pod
      labels:
        name: redis-app
        type: voting-app-demo
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379