apiVersion: v1
kind: Pod
metadata:
  name: redis-app-pod
  labels:
    name: redis-app
    type: voting-app-demo
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379