apiVersion: v1
kind: Service
metadata:
  name: result-app
  labels:
    name: result-service
    type: voting-app-demo
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30005
      targetPort: 80
  selector:
    name: result-app
    type: voting-app-demo