apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app
    type: voting-app-demo
spec:
  containers:
    - name: result-app
      image: babajuneed/examplevotingapp_result
      ports:
        - containerPort: 80