apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app
    type: voting-app-demo
spec:
  containers:
    - name: voting-app
      image: examplevotingapp_vote1
      ports:
        - containerPort: 80