apiVersion: v1
kind: Service
metadata:
  name: voting-app
  labels:
    name: voting-service
    type: voting-app-demo
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30004
      targetPort: 80
  selector:
    name: voting-app
    type: voting-app-demo