apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deploy
  labels:
    app: worker-deploy
    type: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      type: voting-app-demo
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        type: voting-app-demo
    spec:
      containers:
        - name: worker-app
          image: babajuneed/examplevotingapp_worker