apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    type: voting-app-demo
spec:
  containers:
    - name: worker-app
      image: babajuneed/examplevotingapp_worker